from flask import Flask, render_template, jsonify, request
from datetime import datetime
import psutil

app = Flask(__name__)

# =====================================================
# PAGES
# =====================================================

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/monitor")
def monitor():
    return render_template("monitor.html")


# =====================================================
# ✅ REAL LIVE METRICS (NO RANDOM)
# =====================================================

@app.route("/live")
def live():
    return jsonify({
        "cpu": psutil.cpu_percent(interval=1),
        "ram": psutil.virtual_memory().percent,
        "disk": psutil.disk_usage('/').percent,
        "gpu": 0   # GPU optional (needs extra libs)
    })


# =====================================================
# AI SUGGESTIONS (Based on real data)
# =====================================================

@app.route("/ai")
def ai():

    cpu = psutil.cpu_percent()
    ram = psutil.virtual_memory().percent
    disk = psutil.disk_usage('/').percent

    if cpu > 85:
        tip = "⚠ CPU very high — close heavy apps"
    elif ram > 85:
        tip = "⚠ RAM almost full — restart recommended"
    elif disk > 90:
        tip = "⚠ Disk nearly full — cleanup required"
    else:
        tip = "✅ System healthy"

    return jsonify({"tip": tip})


# =====================================================
# 30 DAY FORECAST (still simulated)
# =====================================================

@app.route("/forecast")
def forecast():
    import random
    return jsonify([random.randint(30, 95) for _ in range(30)])


# =====================================================
# DAILY REPORT DOWNLOAD (REAL DATA)
# =====================================================

@app.route("/day_report/<int:day>")
def day_report(day):

    cpu = psutil.cpu_percent()
    ram = psutil.virtual_memory().percent
    disk = psutil.disk_usage('/').percent
    gpu = 0

    status = "GOOD"
    suggestion = "System stable"

    if cpu > 80 or ram > 85:
        status = "HIGH LOAD"
        suggestion = "Close heavy background apps"

    if cpu > 92:
        status = "CRITICAL"
        suggestion = "Immediate optimization required"

    lines = [
        "====================================",
        f"DAILY MONITORING REPORT - Day {day}",
        "====================================",
        f"Generated : {datetime.now()}",
        "",
        "SYSTEM USAGE:",
        f"CPU  : {cpu}%",
        f"RAM  : {ram}%",
        f"DISK : {disk}%",
        f"GPU  : {gpu}%",
        "",
        f"HEALTH STATUS : {status}",
        "",
        "AI SUGGESTION:",
        suggestion,
        "",
        "Generated by AI Predictive Monitoring"
    ]

    return "\n".join(lines), 200, {
        "Content-Type": "application/octet-stream",
        "Content-Disposition": f"attachment; filename=day_{day}_report.txt"
    }


# =====================================================
# 30 DAY SUMMARY DOWNLOAD (REAL BASED)
# =====================================================

@app.route("/summary_report")
def summary_report():

    cpu = psutil.cpu_percent()
    ram = psutil.virtual_memory().percent
    disk = psutil.disk_usage('/').percent
    gpu = 0

    suggestion = "System healthy"

    if cpu > 80 or ram > 80:
        suggestion = "Reduce heavy background tasks"

    lines = [
        "================================================",
        "30 DAY SYSTEM MONITORING SUMMARY REPORT",
        "================================================",
        f"Generated : {datetime.now()}",
        "",
        "CURRENT SYSTEM STATUS:",
        f"CPU  : {cpu}%",
        f"RAM  : {ram}%",
        f"DISK : {disk}%",
        f"GPU  : {gpu}%",
        "",
        "AI SUGGESTION:",
        suggestion,
        "",
        "Prediction:",
        "System expected to remain stable if usage stays similar.",
        "Monitor heavy applications regularly.",
        "Keep disk space above 20%."
    ]

    return "\n".join(lines), 200, {
        "Content-Type": "application/octet-stream",
        "Content-Disposition": "attachment; filename=30_day_summary_report.txt"
    }


# =====================================================
# 🤖 AI CHAT COMPANION (REAL DATA)
# =====================================================
@app.route("/ai_chat", methods=["POST"])
def ai_chat():

    q = request.json["q"].lower()

    cpu = psutil.cpu_percent()
    ram = psutil.virtual_memory().percent
    disk = psutil.disk_usage('/').percent

    # =========================
    # 🔴 CRITICAL CONDITIONS
    # =========================

    if cpu > 90 or ram > 90 or disk > 95:
        return jsonify({
            "reply":
            f"⚠ CRITICAL ALERT!\n"
            f"CPU:{cpu}% RAM:{ram}% Disk:{disk}%\n"
            "Immediate action recommended to avoid system crash."
        })

    # =========================
    # 📊 SYSTEM STATUS
    # =========================

    if "status" in q or "health" in q:
        return jsonify({
            "reply":
            f"System Status → CPU:{cpu}% | RAM:{ram}% | Disk:{disk}%\n"
            "Overall system is stable and operational ✅"
        })

    if "cpu" in q:
        return jsonify({
            "reply":
            f"CPU usage is {cpu}%.\n"
            + ("Processor is under heavy load 😅" if cpu > 80 else "CPU performance is normal 👍")
        })

    if "ram" in q or "memory" in q:
        return jsonify({
            "reply":
            f"RAM usage is {ram}%.\n"
            + ("Memory almost full — close background apps." if ram > 80 else "Memory usage is healthy.")
        })

    if "disk" in q or "storage" in q:
        return jsonify({
            "reply":
            f"Disk usage is {disk}%.\n"
            + ("Storage space running low ⚠" if disk > 85 else "Storage capacity is sufficient.")
        })

    # =========================
    # 🔮 PREDICTION
    # =========================

    if "predict" in q or "future" in q or "slow" in q:
        return jsonify({
            "reply":
            "Based on current usage patterns, system performance is expected to remain stable.\n"
            "High load may occur during intensive tasks."
        })

    # =========================
    # 🛠 SUGGESTIONS
    # =========================

    if "suggest" in q or "improve" in q or "optimize" in q:
        return jsonify({
            "reply":
            "Optimization Tips:\n"
            "• Close unused applications\n"
            "• Restart system periodically\n"
            "• Keep at least 20% disk free\n"
            "• Limit heavy background processes"
        })

    # =========================
    # ⚠ PROBLEM CHECK
    # =========================

    if "problem" in q or "issue" in q or "risk" in q:
        return jsonify({
            "reply":
            "No critical anomalies detected.\n"
            "All components operating within safe limits."
        })

    # =========================
    # 💬 NORMAL CHAT
    # =========================

    if "hello" in q or "hi" in q or "hey" in q:
        return jsonify({
            "reply":
            "Hello  I am your PRESYMON BOT.\n"
            "I monitor your system 24/7."
        })

    if "who are you" in q:
        return jsonify({
            "reply":
            "I am an AI companion designed to analyze system health and predict potential issues."
        })

    if "how are you" in q:
        return jsonify({
            "reply":
            "Operating at optimal efficiency 🚀"
        })

    if "thank" in q:
        return jsonify({
            "reply":
            "You're welcome 😊"
        })

    if "joke" in q:
        return jsonify({
            "reply":
            "Why don’t computers panic?\nBecause they keep their cache 😎"
        })

    if "bored" in q:
        return jsonify({
            "reply":
            "Maybe close some tabs… or touch grass 🌱"
        })

    if "help" in q:
        return jsonify({
            "reply":
            "You can ask about:\n"
            "• CPU usage\n• RAM status\n• Disk health\n"
            "• System prediction\n• Optimization tips"
        })

    # =========================
    # DEFAULT RESPONSE
    # =========================

    return jsonify({
        "reply":
        "Monitoring active 🛰️\n"
        "Ask me about system status, performance, or predictions."
    })
# =====================================================
# RUN SERVER
# =====================================================

if __name__ == "__main__":
    app.run(debug=True)